### ISSUE TITLE
How to edit data in Openeyes

### ISSUE THREAD

**Issue by drswapnil** [openeyes/oe_installer#1]
hi
I was able to get Openeyes installed in Vagrant box and am able to log in into the system through localhost:8888

The problem i am facing now is that i am unable to enter any data in the system. eg. can't enter any new patients of any new site to the system.

i checked the permission of the /var/www/openeyes/assets, cache and /protected directories with the "stat" command. all the directories show  access : 0777 drwxrwxrwx. 

can you pls help

**Comment by drswapnil** [comment]
hi

found the solution... need to use both username at the login prompt as "vagrant" and then when asked the password is also "vagrant"

only after logging in with both username and password as vagrant, can the sudo install commond be used.

**Comment by antonypenn** [comment]
Have you checked the protected/runtime/application.log file for errors?

**Comment by drswapnil** [comment]
yes i did. there is nothing there with just a single line noting that admin logged in at a certain time.

plus i dont understand something else. the vagrant box terminal has changed automatically from the routine white on black to a blue red on black prompt. plus it has become very very slow to respond to commands. can't figureout whats wrong with it.

thanks

**Comment by drswapnil** [comment]
Just to clarify my situation...

I am running windows 7 as my primary OS with openeyes installed at c:/openeyes. I run vagrant through the same. Have installed everything in vagrant box as per instructions. Have not been able to figure out "Windows does not provide a shell facility. To run the commands, either install Git Shell or Putty SSH. You shell to the VM box at 192.168.0.100" these lines. Have not been able to follow "Once built, run vagrant ssh" this command ... (Both these lines are there in the readme.md of the oe_installer).

I have been running openeyes through chrome on windows. Am able to login as admin and am able to see the data entered for the patient Violet Coffin but am unable to either edit her data or to add any new patient.

Thanks

**Comment by antonypenn** [comment]
Hi,

You cannot add patients directly to the system. Data is normally imported via a PAS module (Patient Administration System). We have MEHPAS for moorfields, and I see a FhirPas module developed by someone else.

The coloured prompt displays which git branch you are on, but on some windows systems the shared folders support is very slow, making this command slow. You can remove it by editing the file /etc/bash.bashrc and replacing the line PS1=... with:
PS1="\u@\h \w> "

**Comment by drswapnil** [comment]
Can you pls tell me how to install that. Does this mean that the openeyes
is just a backend database type system without a data entry interface??? or in other words the whole installation till date supports only a hobbled system

**Comment by antonypenn** [comment]
Hi,

There is nothing 'hobbled' about the system. It is designed to interface to patient database systems that are already in place in hospitals. Therefore it does not work standalone. If you want to use it as a standalone system and add patients to it directly, then a patient module can be developed for you. However this would incur cost.

**Comment by drswapnil** [comment]
Hi

Sorry if my wordings offended you. It's just that, at current state,
openeyes is not a complete system which can be directly deployed. As you
said, it has been developed to interface with the system already in place
in moorefields. However this is not apparent at any place on your website.
It was a bit disheartening for me to learn that without the frontend
system, openeyes will not work.

Thanks for all the help though.

**Comment by vetusko** [comment]
Hi,

You can try the add patient module, it's not finished, and never been tested, but you can try it: 

https://github.com/openeyes/AddPatient/tree/develop
